-- REVOKE SELECT 
REVOKE SELECT ON ALL TABLES IN SCHEMA "public" FROm p6dell;

-- REVOKE SELECT 
REVOKE INSERT ON ALL TABLES IN SCHEMA "public" FROM p6dell;

-- REVOKE UPDATE 
REVOKE UPDATE ON ALL TABLES IN SCHEMA "public" FROM p6dell;

-- REVOKE DELETE 
REVOKE DELETE ON ALL TABLES IN SCHEMA "public" FROM p6dell;
